[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.0"
version_files = ["version.txt"]
tag_format = "v$version"
bump_message = "bump: version $current_version → $new_version"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
